### ISSUE TITLE
request new feature

### ISSUE THREAD

**Issue by ItzKazuki** [ItzKazuki/web-sertifikat-digital#4]
Tambah filtur **tambah template sertifikat**

kelebihan:
- bisa banyak nambah template
- bisa ubah ubah template
- bisa di hapus/dimanipulasi templatenya

kekuarangan:
- bikin tampilan lagi

**Comment by ItzKazuki** [comment]
worth it ga @0rcaaa

**Comment by ItzKazuki** [comment]
review dong om @0rcaaa ada yang kureng ga dari filtur nya

**Comment by 0rcaaa** [comment]
tampilan apa

**Comment by 0rcaaa** [comment]
itu ui buat download serif udh ad?

**Comment by ItzKazuki** [comment]
> itu ui buat download serif udh ad?

udh di bagian cek sertifikat

**Comment by ItzKazuki** [comment]
nanti bikin cek sertifikat berdasarkan nik juga dah ntr gw bikin

**Comment by 0rcaaa** [comment]
okay
