### ISSUE TITLE
error while edit certificate

### ISSUE THREAD

**Issue by ItzKazuki** [ItzKazuki/web-sertifikat-digital#8]
![image](https://github.com/user-attachments/assets/9864c22e-8427-4257-a41a-a50e725e6164)
bug while update certificate, how to fix this??

**Comment by ItzKazuki** [comment]
pls help @0rcaaa

**Comment by 0rcaaa** [comment]
wait, lu masukin gambar ke dB?

**Comment by ItzKazuki** [comment]
eh engga deh, itu error depraceted, function lama masih bisa cuman ga di saranin

how to fix this?

```php
error_reporting(E_ALL & ~E_DEPRECATED);
```

change to that in line 19 at service/certificate.php

**Comment by ItzKazuki** [comment]
![image](https://github.com/user-attachments/assets/d75ea360-1306-4d8f-bf95-0b4bcf1cea07)
ini doang tinggal

**Comment by ItzKazuki** [comment]
kwkw bikin reports brwooh

**Comment by ItzKazuki** [comment]
![image](https://github.com/user-attachments/assets/96477614-655b-4efe-9223-7df082bceb27)
fixed!

**Comment by ItzKazuki** [comment]
wwkwk turu bang @0rcaaa

**Comment by ItzKazuki** [comment]
> wait, lu masukin gambar ke dB?

engga itu buat filtur laporan
